plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modImplementation "dev.architectury:architectury-fabric:${project.architectury_version}"

    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"

    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"

    modImplementation("io.github.flemmli97:debugutils:${project.debugutils_version}-fabric") {
        transitive = false
    }

    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}") {
        transitive = false
    }

    modRuntimeOnly "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"

    modRuntimeOnly "net.fabricmc:fabric-language-kotlin:${project.fabric_language_kotlin_version}"

    modRuntimeOnly "maven.modrinth:nbt-autocomplete:${project.nbt_autocomplete_version}-fabric-1.21.11"

    modRuntimeOnly "maven.modrinth:spark:${project.spark_version}-fabric"

    common(project(path: ":common", configuration: "namedElements")) {
        transitive = false
    }

    shadowBundle project(path: ":common", configuration: "transformProductionFabric")
}

fabricApi {
    configureDataGeneration()
}

shadowJar {
    configurations = [project.configurations.shadowBundle]

    archiveClassifier.set("dev-shadow")

    exclude "architectury.common.json"
}

remapJar {
    inputFile.set(shadowJar.archiveFile)

    dependsOn shadowJar

    injectAccessWidener = true

    archiveClassifier.set(null)
}